image: rust:latest

stages:
  - build
  - test

build:
  stage: build
  script: "cargo build --release"

test:
  stage: test
  script: "cargo test  --release"

clippy:
  stage: test
  allow_failure: true
  script: "cargo clippy --release -- -D warnings"