[package]
name = "rta-for-fps"
version = "0.1.0"
authors = ["Bennet Bleßmann <bennet.blessmann@stu.uni-kiel.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
